# EXCEL로 만든 인공신경망을 pytorch의 Tensor 클래스을 이용하여 만들기

In [1]:
import torch

필요한 함수의 정의하기

In [2]:
def ReLU_func(outputs):
    final_outputs=torch.zeros(outputs.size()[0],outputs.size()[1])
    for i in range(outputs.size()[0]):
        for j in range(outputs.size()[1]):
            final_outputs[i][j]=max(0,outputs[i][j])
    return final_outputs


def softmax(outputs):
    outputs_list=[]  
    softmax=torch.zeros(outputs.size()[0],outputs.size()[1])
    for i in range(outputs.size()[0]):
        exp_a = torch.exp(outputs[i]-max(outputs[i]))
        sum_num = torch.sum(exp_a)
        out = exp_a/sum_num
        outputs_list.append(out)
        
    for i in range(outputs.size()[0]):
        for j in range(outputs.size()[1]):
            softmax[i][j]=outputs_list[i][j]
    
    return softmax



def cross_entropy(outputs, labels):
    cross_entropy=torch.zeros(outputs.size()[0])
    outputs_list=[]
    for i in range(outputs.size()[0]):

        outputs_list.append(-torch.sum(labels[i]*torch.log(outputs[i])))
            
            

    for i in range(outputs.size()[0]):
        cross_entropy[i]=outputs_list[i]
            
    return cross_entropy


Weight 값 설정하기

In [3]:
w_ih = torch.Tensor([[1, -2,3],
                       [ -2,5,3]
                      ])
w_ho = torch.Tensor([[3, -2, 4],
                       [-1, 2, 3],
                       [2, -2, -4]
                      ])

Batch 가 3인 Input 값과 Labels 값의 입력하기

In [4]:
input = torch.Tensor([[2, -4],
                       [0, 3],
                       [-6, 2]
                      ])
labels = torch.Tensor([[1, 0, 0],
                       [0, 1, 0],
                       [0, 0, 1]
                      ])

L1의 활성화 함수 전의 값 구하기

In [5]:
L1 = torch.matmul(input,w_ih)
print(L1)

tensor([[ 10., -24.,  -6.],
        [ -6.,  15.,   9.],
        [-10.,  22., -12.]])


ReLU의 적용하기

In [6]:
L1 = ReLU_func(torch.matmul(input,w_ih))
print(L1)

tensor([[10.,  0.,  0.],
        [ 0., 15.,  9.],
        [ 0., 22.,  0.]])


Output 구하기

In [7]:
outputs = torch.matmul(L1,w_ho)
print(outputs)

tensor([[ 30., -20.,  40.],
        [  3.,  12.,   9.],
        [-22.,  44.,  66.]])


Softmax의 적용

In [8]:
so = softmax(outputs)
print(so)

tensor([[4.5398e-05, 8.7561e-27, 9.9995e-01],
        [1.1754e-04, 9.5246e-01, 4.7420e-02],
        [6.0546e-39, 2.7895e-10, 1.0000e+00]])


sample별로 loss 구하기

In [9]:
loss = cross_entropy(so,labels)
print(loss)

tensor([10.0000,  0.0487, -0.0000])


최종 loss 구하기

In [10]:
loss = loss.mean(dim=0).item()
print(loss)

3.349583625793457


## EXCEL과 같은 답이 나오는가?

 #### 아니면 이유가 무엇인가? 


같다. 내가 만든 함수의 경우에는 cross_entropy를 구할때 정해진 식에 맞게 계산을 하였기 때문이다. 하지만 torch.nn.CrossEntrophyLoss를 사용해서 cross_entropy를 만들었다면 값이 다르게 나올 수도 있을 것이다. 왜냐하면 torch.nn.CrossEntrophyLoss는 cross_entorpy 연산 외에도, softmax와 log처리도 함께 도와주기 때문이다.