In [1]:
import torch
import numpy as np
import matplotlib.pyplot as plt

device = "cuda:0" if torch.cuda.is_available() else "cpu"
device

'cpu'

In [2]:
torch.__version__

'1.11.0'

In [3]:
# numpy array 생성
a = np.ones((2, 3))
# tensor  생성
b = torch.tensor(a)
# dtype
print(a.dtype, '\t', b.dtype)

float64 	 torch.float64


In [6]:
x=torch.tensor([[1,2,3],[4,5,6]])
print(x)
x[0][0].item()

tensor([[1, 2, 3],
        [4, 5, 6]])


1

In [7]:
a = torch.tensor([1,2,3,4,5,6])
print(a)

tensor([1, 2, 3, 4, 5, 6])


In [8]:
a=torch.FloatTensor
print(a)

<class 'torch.FloatTensor'>


In [9]:
a.dtype

torch.float32

In [10]:
x=torch.rand(5,3)
x

tensor([[0.5313, 0.9878, 0.7174],
        [0.6628, 0.9012, 0.2853],
        [0.7429, 0.9906, 0.2620],
        [0.2982, 0.1555, 0.6002],
        [0.7670, 0.1001, 0.3897]])

In [11]:
x

tensor([[0.5313, 0.9878, 0.7174],
        [0.6628, 0.9012, 0.2853],
        [0.7429, 0.9906, 0.2620],
        [0.2982, 0.1555, 0.6002],
        [0.7670, 0.1001, 0.3897]])

In [12]:
x.dtype

torch.float32

In [13]:
x.size()

torch.Size([5, 3])

In [14]:
x=torch.zeros(5,3)

In [15]:
x

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [16]:
x=torch.zeros(5,3,dtype=torch.long)

In [21]:
x

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [22]:
x.shape

torch.Size([5, 3])

In [24]:
x.ndimension()

2

In [25]:
x.reshape(3,5)

tensor([[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]])

In [26]:
x

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [28]:
x=x.reshape(3,5)

In [29]:
x

tensor([[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]])

In [30]:
x.view(5,3)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [31]:
x

tensor([[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]])

In [34]:
x=x.view(5,3)#데이터가 연속적이지 않은 경우 ex.transpose의 경우에는 reshape를 써야함

In [35]:
x

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])