In [10]:
import torch
import numpy as np
import matplotlib.pyplot as plt

device = "cuda:0" if torch.cuda.is_available() else "cpu"
device

'cpu'

In [11]:
numpy_array = np.array([0.0, 1.0, 2.0, 3.0, 4.0, 5.0])       # numpy array
torch_tensor = torch.from_numpy(numpy_array)               # torch tensor
torch_tensor 

tensor([0., 1., 2., 3., 4., 5.], dtype=torch.float64)

In [13]:
back_to_numpy=torch_tensor.numpy()
back_to_numpy

array([0., 1., 2., 3., 4., 5.])

In [14]:
back_to_numpy[-1]=100

In [15]:
back_to_numpy

array([  0.,   1.,   2.,   3.,   4., 100.])

In [16]:
back_to_numpy

array([  0.,   1.,   2.,   3.,   4., 100.])

In [18]:
numpy_array # 값 하나를 바꾸면 서로 메모리를 공유함

array([  0.,   1.,   2.,   3.,   4., 100.])